spring:
  central-datasource:
    jdbc-url: jdbc:mariadb://89.35.130.223:3306/s4_WorkSwap_Center?useSSL=false&serverTimezone=UTC
    username: u4_Uyj3V7Gjcz
    password: rpV9iwJQ8CdFP@spOqa37E+N
    driver-class-name: org.mariadb.jdbc.Driver

    connection-timeout: 30000
    minimum-idle: 2
    maximum-pool-size: 10
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 30000
    validation-timeout: 5000
    keepalive-time: 300000
  statistics-datasource:
    jdbc-url: jdbc:mariadb://89.35.130.223:3306/s4_WorkSwap_Statistic?useSSL=false&serverTimezone=UTC
    username: u4_ZLyMrRoZvC
    password: TuLL0.ml^LWphx9xdriw6TVn
    driver-class-name: org.mariadb.jdbc.Driver
    
    connection-timeout: 30000
    minimum-idle: 2
    maximum-pool-size: 10
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 30000
    validation-timeout: 5000
    keepalive-time: 300000
  admin-datasource:
    jdbc-url: jdbc:mariadb://89.35.130.223:3306/s4_WorkSwap_Admin?useSSL=false&serverTimezone=UTC
    username: u4_f3Cuj9bs4p
    password: 29AM+l!^63qgh9gKgFI@kGr3
    driver-class-name: org.mariadb.jdbc.Driver
    
    connection-timeout: 30000
    minimum-idle: 2
    maximum-pool-size: 10
    idle-timeout: 600000
    max-lifetime: 1800000
    leak-detection-threshold: 30000
    validation-timeout: 5000
    keepalive-time: 300000