spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
  central-datasource:
    jdbc-url: jdbc:mysql://89.35.130.223:3306/s4_WorkSwap_Center?useSSL=false&serverTimezone=UTC
    username: u4_Uyj3V7Gjcz
    password: rpV9iwJQ8CdFP@spOqa37E+N
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 600000
      maxLifetime: 1800000 
  statistics-datasource:
    jdbc-url: jdbc:mysql://89.35.130.223:3306/s4_WorkSwap_Statistic?useSSL=false&serverTimezone=UTC
    username: u4_ZLyMrRoZvC
    password: TuLL0.ml^LWphx9xdriw6TVn
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: false
  admin-datasource:
    jdbc-url: jdbc:mysql://89.35.130.223:3306/s4_WorkSwap_Admin?useSSL=false&serverTimezone=UTC
    username: u4_f3Cuj9bs4p
    password: 29AM+l!^63qgh9gKgFI@kGr3
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      maximumPoolSize: 10
      minimumIdle: 5
      idleTimeout: 600000
      maxLifetime: 1800000
      autoCommit: false