logging:
  level:
    org.workswap.main.controller.advice.GlobalExceptionHandler: INFO
    org.workswap.config.SecurityConfig: INFO

    org.workswap.main.controller.components.ApiChatController: INFO  
    org.workswap.main.controller.components.ChatWebSocketController: INFO

    org.workswap.main.controller.secure.OwnListingController: INFO
    
    org.workswap.core.services.UserService: INFO
    org.workswap.core.services.ListingService: INFO
    org.workswap.core.services.ChatService: INFO
    org.workswap.core.services.CategoryService: INFO
    org.workswap.core.services.StatService: INFO
    org.workswap.core.services.LocalizationService: INFO
    org.workswap.core.services.NotificationService: INFO
    
    org.workswap.core.services.components.AuthService: INFO
    org.workswap.core.services.components.LangFileScheduler: INFO

    org.workswap.core.services.components.security.CustomOAuth2SuccessHandler: DEBUG

    org.springframework.web.multipart: INFO
    org.springframework.web.servlet.resource: INFO
    org.springframework.security: DEBUG