logging:
  level:
    org.workswap.config.SecurityConfig: INFO
    org.workswap.config.WebSocketConfig: INFO

    org.workswap.api.controller.ChatController: INFO  
    org.workswap.api.controller.ChatWebSocketController: DEBUG

    org.workswap.api.controller.UploadController: INFO
    org.workswap.api.controller.AuthController: DEBUG
    
    org.workswap.core.services.UserService: INFO
    org.workswap.core.services.ChatService: INFO
    org.workswap.core.services.CategoryService: INFO
    org.workswap.core.services.StatService: INFO
    org.workswap.core.services.LocalizationService: INFO
    org.workswap.core.services.NotificationService: INFO 
    org.workswap.core.services.ReviewService: INFO

    org.workswap.core.services.query.ListingQueryService: INFO
    org.workswap.core.services.command.PermissionCommandService: INFO
    org.workswap.core.services.command.ListingCommandService: INFO
    
    org.workswap.core.services.components.AuthService: INFO
    org.workswap.core.services.components.LangFileScheduler: INFO

    org.workswap.core.services.security.authentication.CustomOAuth2SuccessHandler: INFO
    org.workswap.core.services.security.authentication.CustomOAuth2FailureHandler: INFO
    org.workswap.core.services.security.AuthChannelInterceptor: INFO
    org.workswap.core.services.security.JwtTokenConverter: INFO

    org.workswap.core.services.rabbitmq.ReviewProducer: INFO

    org.springframework.web.multipart: INFO
    org.springframework.web.servlet.resource: INFO
    org.springframework.security: INFO

    com.zaxxer.hikari: INFO
    org.hibernate.SQL: INFO